name: resty
version: 0.1.0
homepage: https://github.com/hsul4n/dart-resty
description: A simple, light and useful http wrapper built above dart's http core library.
environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test: ^1.3.0
